name: projet_dev
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  flutter_circle_color_picker: ^0.3.0
  flutter_svg: ^0.22.0
  font_awesome_flutter: ^9.1.0
  google_fonts: ^2.1.0
  http: ^0.13.3
  fluttertoast: ^8.1.2
  rflutter_alert: ^2.0.4
  
  firebase_core: ^2.4.1
  firebase_database: ^10.0.9
  percent_indicator: ^4.2.2



dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
   